module.exports = global.config = {
  role: {
    cpm: "you.siong.hong@ericsson.com;mohd.najmuddin.yusoff@ericsson.com;sey.loy.lee@ericsson.com;",
  },
  cpo_mapping: {
    hw: {
      header: [
        "DEAL NAME",
        "HAMMER ",
        "PROJECT DESCRIPTION",
        "PO NUMBER",
        "1",
        "LOOKUP REFERENCE",
        "REGION",
        "REFERENCE LOC ID",
        "NEW LOC ID",
        "SITE NAME",
        "NEW SITE NAME",
        "CONFIG",
        "PO#",
        "LINE",
        "LINE ITEM SAP CELCOM",
        "MATERIAL CODE",
        "DESCRIPTION",
        "QTY",
        "NW#",
        "ON AIR DATE",
        "MAPPING DATE",
        "REMARKS",
        "GR NO",
        "PROCEED BILLING 100%",
        "CELCOM USER",
        "PCODE",
        "UNIT PRICE",
        "TOTAL PRICE",
        "DISCOUNTED UNIT PRICE",
        "DISCOUNTED PO PRICE",
        "NET UNIT PRICE",
        "INVOICE TOTAL",
        "HAMMER 1 HD TOTAL",
        "SO LINE ITEM DESCRIPTION",
        "sitePCode",
        "VlookupWBS",
        "SO NO.",
        "WBS  NO.",
        "FOR CHECKING PURPOSE ONLY-RASHIDAH",
        "HW COA RECEIVED DATE",
        "80% BILLING UPON HW COA",
        "80% INVOICING NO.",
        "80% INVOICING DATE",
        "Cancel Invoice",
        "NI COA DATE (VLOOKUP FROM SERVICES MAPPING)",
        "20% BILLING UPON NI",
        "20% INVOICING NO.",
        "20% INVOICING DATE",
        "Cancelled",
        "HW COA RECEIVED DATE",
        "40% BILLING UPON COA HW",
        "40% INVOICING NO.",
        "40% INVOICING DATE",
        "Cancelled",
        "NI COA date (vlookup from SERVICES MAPPING)",
        "40% BILLING UPON COA NI",
        "40% INVOICING Number",
        "40% INVOICING DATE",
        "Cancelled",
        "SSO COA date (vlookup from SERVICES MAPPING)",
        "20% BILLING UPON COA SSO",
        "20% INVOICING NO.",
        "20% INVOICING DATE",
        "Cancelled",
        "100%  HW COA ",
        "100% BILLING UPON HW COA",
        "100% INVOICING NO.",
        "100% INVOICING DATE",
        "Cancelled",
        "Cancel column",
        "REFERENCE LOC ID",
        "PO#",
        "REFF",
        "Vlookup for billing",
      ],
      header_model: [
        "Deal_Name",
        "Hammer",
        "Project_Description",
        "Po_Number",
        "Data_1",
        "Lookup_Reference",
        "Region",
        "Reference_Loc_Id",
        "New_Loc_Id",
        "Site_Name",
        "New_Site_Name",
        "Config",
        "Po",
        "Line",
        "Line_Item_Sap",
        "Material_Code",
        "Description",
        "Qty",
        "NW",
        "On_Air_Date",
        "Mapping_Date",
        "Remarks",
        "Gr_No",
        "Proceed_Billing_100",
        "Celcom_User",
        "Pcode",
        "Unit_Price",
        "Total_Price",
        "Discounted_Unit_Price",
        "Discounted_Po_Price",
        "Net_Unit_Price",
        "Invoice_Total",
        "Hammer_1_Hd_Total",
        "So_Line_Item_Description",
        "Sitepcode",
        "VlookupWbs",
        "So_No",
        "Wbs_No",
        "For_Checking_Purpose_Only_Rashidah",
        "Hw_Coa_Received_Date_80",
        "Billing_Upon_Hw_Coa_80",
        "Invoicing_No_Hw_Coa_80",
        "Invoicing_Date_Hw_Coa_80",
        "Cancelled_Invoice_Hw_Coa_80",
        "Ni_Coa_Date_20",
        "Billing_Upon_Ni_20",
        "Invoicing_No_Ni_20",
        "Invoicing_Date_Ni_20",
        "Cancelled_Invoicing_Ni_20",
        "Hw_Coa_Received_Date_40",
        "Billing_Upon_Hw_Coa_40",
        "Invoicing_No_Hw_Coa_40",
        "Invoicing_Date_Hw_Coa_40",
        "Cancelled_Hw_Coa_40",
        "Ni_Coa_Date_40",
        "Billing_Upon_Ni_40",
        "Invoicing_No_Ni_40",
        "Invoicing_Date_Ni_40",
        "Cancelled_Ni_40",
        "Sso_Coa_Date_20_1",
        "Billing_Upon_Sso_20_1",
        "Invoicing_No_Sso_20_1",
        "Invoicing_Date_Sso_20_1",
        "Cancelled_Sso_20",
        "Hw_Coa_100",
        "Billing_Upon_Hw_Coa_100",
        "Invoicing_No_Hw_Coa_100",
        "Invoicing_Date_Hw_Coa_100",
        "Cancelled_Invoicing_Hw_Coa_100",
        "Cancel_Column",
        "Reference_Loc_Id_1",
        "Po_1",
        "Reff",
        "Vlookup_For_Billing",
      ],
      header_materialmapping: [
        "Deal_Name",
        "Hammer",
        "Project_Description",
        "Po_Number",
        "Data_1",
        "Lookup_Reference",
        "Region",
        "Reference_Loc_Id",
        "New_Loc_Id",
        "Site_Name",
        "New_Site_Name",
        "Config",
        "Po",
        "Line",
        "Line_Item_Sap",
        "Material_Code",
        "Description",
        "Qty",
        "NW",
        "On_Air_Date",
        "Mapping_Date",
        "Remarks",
        "Gr_No",
        "Premr_No",
        "Proceed_Billing_100",
        "Celcom_User",
        "Pcode",
        "Unit_Price",
        "Total_Price",
        "Discounted_Unit_Price",
        "Discounted_Po_Price",
      ],
      header_pfm: [
        "So_Line_Item_Description",
        "Sitepcode",
        "VlookupWbs",
        "So_No",
        "Wbs_No",
        "Hw_Coa_Received_Date_80",
        "Billing_Upon_Hw_Coa_80",
        "Invoicing_No_Hw_Coa_80",
        "Invoicing_Date_Hw_Coa_80",
        "Cancelled_Invoice_Hw_Coa_80",
        "Billing_Upon_Ni_20",
        "Invoicing_No_Ni_20",
        "Invoicing_Date_Ni_20",
        "Cancelled_Invoicing_Ni_20",
        "Billing_Upon_Hw_Coa_40",
        "Invoicing_No_Hw_Coa_40",
        "Invoicing_Date_Hw_Coa_40",
        "Cancelled_Hw_Coa_40",
        "Billing_Upon_Ni_40",
        "Invoicing_No_Ni_40",
        "Invoicing_Date_Ni_40",
        "Cancelled_Ni_40",
        "Billing_Upon_Sso_20_1",
        "Invoicing_No_Sso_20_1",
        "Invoicing_Date_Sso_20_1",
        "Cancelled_Sso_20",
        "Hw_Coa_100",
        "Invoicing_No_Hw_Coa_100",
        "Invoicing_Date_Hw_Coa_100",
        "Cancelled_Invoicing_Hw_Coa_100",
      ],
      header_admin: [
        "For_Checking_Purpose_Only_Rashidah",
        "Hw_Coa_Received_Date_40",
        "Hw_Coa_Received_Date_80",
        "Hw_Coa_100",
        "Invoicing_Date_Hw_Coa_100",
        "Cancel_Column",
        "Reference_Loc_Id_1",
        "Reff",
      ],
    },
    svc: {
      header: [
        "DEAL NAME",
        "HAMMER ",
        "PROJECT DESCRIPTION",
        "PO NUMBER",
        "1",
        "LOOKUP REFERENCE",
        "REGION",
        "REFERENCE LOC ID",
        "NEW LOC ID",
        "SITE NAME",
        "NEW SITE NAME",
        "CONFIG",
        "PO#",
        "LINE",
        "MATERIAL CODE",
        "LINE ITEM SAP CELCOM",
        "DESCRIPTION",
        "QTY",
        "CNI DATE",
        "MAPPING DATE",
        "REMARKS",
        "GR NO",
        "PROCEED BILLING 100%",
        "CELCOM USER",
        "PCODE",
        "UNIT PRICE",
        "TOTAL PRICE",
        "COMMODITY",
        "DISCOUNTED UNIT PRICE",
        "DISCOUNTED PO PRICE",
        "NET UNIT PRICE",
        "INVOICE TOTAL",
        "HAMMER 1 HD TOTAL",
        "SO LINE ITEM DESCRIPTION",
        "sitePCode",
        "VlookupWBS",
        "SO NO.",
        "WBS  NO.",
        "100% BILLING",
        "ATP COA DATE RECEIVED",
        "80% BILLING UPON ATP",
        "80% INVOICING NO.",
        "80% INVOICING DATE",
        "Cancelled",
        "COA NI DATE RECEIVED",
        "20% BILLING UPON NI",
        "20% INVOICING NO.",
        "20% INVOICING DATE",
        "Cancelled",
        "COA SSO RCVD DATE",
        "80% BILLING UPON SSO",
        "80% INVOICING NO.",
        "80% INVOICING DATE",
        "Cancelled",
        "COA PSP RCVD DATE 20%",
        "20% BILLING UPON PSP",
        "20% INVOICING NO.",
        "20% INVOICING DATE",
        "Cancelled",
        "COA NI RCVD DATE",
        "40% BILLING UPON NI",
        "40% INVOICING NO.",
        "40% INVOICING DATE",
        "Cancelled",
        "COSSO RCVD DATE",
        "60% BILLING UPON SSO",
        "60% INVOICING NO.",
        "60% INVOICING DATE",
        "Cancelled",
        "COA SSO RCVD DATE 100%",
        "100% BILLING UPON SSO",
        "100% INVOICING NO.",
        "100% INVOICING DATE",
        "Cancelled",
        "COA NI RCVD DATE 100%",
        "100% BILLING UPON NI",
        "100% INVOICING NO.",
        "100% INVOICING DATE",
        "Cancelled",
        "SES NO.",
        "SES STATUS",
        "LINK",
        "NI COA SUBMISSION STATUS",
      ],

      header_model: [
        "Deal_Name",
        "Hammer",
        "Project_Description",
        "Po_Number",
        "Data_1",
        "Lookup_Reference",
        "Region",
        "Reference_Loc_Id",
        "New_Loc_Id",
        "Site_Name",
        "New_Site_Name",
        "Config",
        "Po",
        "Line",
        "Material_Code",
        "Description",
        "Line_Item_Sap",
        "Qty",
        "CNI_Date",
        "Mapping_Date",
        "Remarks",
        "Gr_No",
        "Proceed_Billing_100",
        "Celcom_User",
        "Pcode",
        "Unit_Price",
        "Total_Price",
        "Commodity",
        "Discounted_Unit_Price",
        "Discounted_Po_Price",
        "Net_Unit_Price",
        "Invoice_Total",
        "Hammer_1_Hd_Total",
        "So_Line_Item_Description",
        "Sitepcode",
        "VlookupWbs",
        "So_No",
        "Wbs_No",
        "Billing_100",
        "Atp_Coa_Received_Date_80",
        "Billing_Upon_Atp_Coa_80",
        "Invoicing_No_Atp_Coa_80",
        "Invoicing_Date_Atp_Coa_80",
        "Cancelled_Atp_Coa_80",
        "Ni_Coa_Date_20",
        "Billing_Upon_Ni_20",
        "Invoicing_No_Ni_20",
        "Invoicing_Date_Ni_20",
        "Cancelled_Invoicing_Ni_20",
        "Sso_Coa_Date_80",
        "Billing_Upon_Sso_80",
        "Invoicing_No_Sso_80",
        "Invoicing_Date_Sso_80",
        "Cancelled_Sso_Coa_Date_80",
        "Coa_Psp_Received_Date_20",
        "Billing_Upon_Coa_Psp_20",
        "Invoicing_No_Coa_Psp_20",
        "Invoicing_Date_Coa_Psp_20",
        "Cancelled_Coa_Psp_Received_Date_20",
        "Coa_Ni_Received_Date_40",
        "Billing_Upon_Coa_Ni_40",
        "Invoicing_No_Coa_Ni_40",
        "Invoicing_Date_Coa_Ni_40",
        "Cancelled_Coa_Ni_Received_Date_40",
        "Cosso_Received_Date_60",
        "Billing_Upon_Cosso_60",
        "Invoicing_No_Cosso_60",
        "Invoicing_Date_Cosso_60",
        "Cancelled_Cosso_Received_Date_60",
        "Coa_Sso_Received_Date_100",
        "Billing_Upon_Sso_Coa_100",
        "Invoicing_No_Sso_Coa_100",
        "Invoicing_Date_Sso_Coa_100",
        "Cancelled_Coa_Sso_Received_Date_100",
        "Coa_Ni_Date_100",
        "Billing_Upon_Coa_Ni_100",
        "Invoicing_No_Coa_Ni_100",
        "Invoicing_Date_Coa_Ni_100",
        "Cancelled_Coa_Ni_Date_100",
        "Ses_No",
        "Ses_Status",
        "Link",
        "Ni_Coa_Submission_Status",
      ],
      header_materialmapping: [
        "Deal_Name",
        "Hammer",
        "Project_Description",
        "Po_Number",
        "Data_1",
        "Lookup_Reference",
        "Region",
        "Reference_Loc_Id",
        "New_Loc_Id",
        "Site_Name",
        "New_Site_Name",
        "Config",
        "Po",
        "Line",
        "Description",
        "Qty",
        "CNI_Date",
        "Mapping_Date",
        "Remarks",
        "Gr_No",
        "Premr_No",
        "Proceed_Billing_100",
        "Celcom_User",
        "Pcode",
        "Unit_Price",
        "Total_Price",
        "Commodity",
        "Discounted_Unit_Price",
        "Discounted_Po_Price",
      ],

      header_pfm: [
        "So_Line_Item_Description",
        "Sitepcode",
        "VlookupWbs",
        "So_No",
        "Wbs_No",
        // "Atp_Coa_Received_Date_80",
        "Billing_Upon_Atp_Coa_80",
        "Invoicing_No_Atp_Coa_80",
        "Invoicing_Date_Atp_Coa_80",
        "Cancelled_Atp_Coa_80",
        // "Ni_Coa_Date_20",
        "Billing_Upon_Ni_20",
        "Invoicing_No_Ni_20",
        "Invoicing_Date_Ni_20",
        "Cancelled_Invoicing_Ni_20",
        // "Sso_Coa_Date_80",
        "Billing_Upon_Sso_80",
        "Invoicing_No_Sso_80",
        "Invoicing_Date_Sso_80",
        "Cancelled_Sso_Coa_Date_80",
        // "Coa_Psp_Received_Date_20",
        "Billing_Upon_Coa_Psp_20",
        "Invoicing_No_Coa_Psp_20",
        "Invoicing_Date_Coa_Psp_20",
        "Cancelled_Coa_Psp_Received_Date_20",
        // "Coa_Sso_Received_Date_100",
        "Billing_Upon_Sso_Coa_100",
        "Invoicing_No_Sso_Coa_100",
        "Invoicing_Date_Sso_Coa_100",
        "Cancelled_Coa_Sso_Received_Date_100",
        "Coa_Ni_Date_100",
        "Billing_Upon_Coa_Ni_100",
        "Invoicing_No_Coa_Ni_100",
        "Invoicing_Date_Coa_Ni_100",
        "Cancelled_Coa_Ni_Date_100",
      ],

      header_admin: [
        "Billing_100",
        "Atp_Coa_Received_Date_80",
        "Ni_Coa_Date_20",
        "Sso_Coa_Date_80",
        "Coa_Psp_Received_Date_20",
        "Coa_Ni_Received_Date_40",
        "Cosso_Received_Date_60",
        "Coa_Sso_Received_Date_100",
        "Coa_Ni_Date_100",
        "Ses_No",
        "Ses_Status",
        "Link",
        "Ni_Coa_Submission_Status",
      ],
    },
    master: {
      header: [
        "Type",
        "Deal_Name",
        "Hammer",
        "Project_Description",
        "Po_Number",
        "Po",
        "Line_Item",
        "LINE ITEM SAP CELCOM",
        "MATERIAL CODE",
        "Description",
        "Qty",

        "RESERVED",
        "CALLOFF",
        "Balance",
        "Unit_Price",
        "Total_Price",
        "Assigned_Price",
        "Discounted_Unit_Price",
        "Discounted_Po_Price",
        "Discounted_Assigned_Price",
        "Hammer_1_Hd",
        "Pcode",
        "Pcode_Used",
        "Commodity",
      ],
      header_model: [
        "type_summary",
        "Deal_Name",
        "Hammer",
        "Project_Description",
        "Po_Number",
        "Po",
        "Line_Item",
        "Line_Item_Sap",
        "Material_Code",
        "Description",
        "Qty",
        "Reserve",
        "Called_Off",
        "Balance",
        "Unit_Price",
        "Total_Price",
        "Assigned_Price",
        "Discounted_Unit_Price",
        "Discounted_Po_Price",
        "Discounted_Assigned_Price",
        "Hammer_1_Hd",
        "Pcode",
        "Pcode_Used",
        "Commodity",
      ],
      header_materialmapping: [
        "hw_svc",
        "Deal_Name",
        "Hammer",
        "Project_Description",
        "Po_Number",
        "Po",
        "Line_Item",
        "Line_Item_Sap",
        "Material_Code",
        "Description",
        "Qty",

        "Unit_Price",

        "Discounted_Unit_Price",

        "Hammer_1_Hd",
        "Pcode",
        "Pcode_Used",
        "Commodity",
      ],
    },
  },
};
